FROM python:latest


# Set working directory for the app
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy application files
COPY Backend/src ./src



# Copy static files
COPY Frontend/build/ /app/build/



# Command to start uvicorn server

#uncomment for local development and use docker compose up
# CMD ["uvicorn", "--reload", "src.app:app", "--host", "0.0.0.0"]

